version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: before-deploy.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: after-deploy.sh
      timeout: 180
      runas: ubuntu
